version: "3.5"

networks:
    webnet:
        name: default-docker-apps-network
        external: true

services:
    rest-app:
        image: rest-app:latest
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "9000:9000"
        volumes:
            - "./:/var/www/html"
        networks:
            - webnet
